### ISSUE TITLE
this is great, thank you

### ISSUE THREAD

**Issue by leafstrat** [surprisetalk/pommy#1]
i appreciate the animated display a lot.

im going to attempt to integrate it with my statusbar so its always visible

**Comment by surprisetalk** [comment]
Status bar sounds like a great idea. 
Are you thinking something like Vim or Tmux?

**Comment by leafstrat** [comment]
i use dwm tiling manager, freakin awesome btw.

so i just do
xsetroot -name "$content"

-------- Original message --------
From Taylor Sarrafian notifications@github.com 
Date: 02-24-2016  6:58 AM  (GMT+00:00) 
To surprisetalk/pommy pommy@noreply.github.com 
Cc Justin Chaschowy jtchaschowy@gmail.com 
Subject Re: [pommy] this is great, thank you (#1) 

Status bar sounds like a great idea. 
Are you thinking something like Vim or Tmux?

**Comment by surprisetalk** [comment]
that's super cool! let me know if there's any features you'd like me to add :)
